### ISSUE TITLE
url-minify(2.8.3) Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined

### ISSUE THREAD

**Issue by prabha190189** [rubiin/url-minify#8]
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined

code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'

**Comment by rubiin** [comment]
can you provide a minimum reproduction. Also are you using in typescript or javascipt

**Comment by rubiin** [comment]
will look into it

**Comment by rubiin** [comment]
Fixed in latest release , also the readme is updated so you should import as
```js
const minify = require('url-minify').default;
```
